# This is a basic workflow that is manually triggered

name: Environment Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : Displaying environment specific 
        run : echo "Deploying to ${{ github.event.inputs.environment }}"
